/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author user
 */
import javax.swing.*;
import java.util.*;
import java.io.*;




public class AddPromoter extends javax.swing.JFrame {
    ArrayList<Promoter> Promoters;

    /**
     * Creates new form AddPromoter
     */
    public AddPromoter() {
        initComponents();
        Promoters = new ArrayList<Promoter>();
        poplulateArryList();
   
    }
    public void poplulateArryList(){
        try{
            FileInputStream file = new FileInputStream("Promoter.dat");
            ObjectInputStream inputFile = new ObjectInputStream(file);
            
            boolean endOfFile = false;
            
            while (!endOfFile){
                try{
                    Promoters.add((Promoter) inputFile.readObject());
                }
                catch(EOFException e){
                    endOfFile = true;
                    
                }
                catch(Exception f){
                    JOptionPane.showMessageDialog(null,f.getMessage());
                    
                }
            }
            inputFile.close();
            
            
        }
        catch(IOException e){
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
        
    }
    public void savePromoterToFile(){
        try{
            FileOutputStream file = new FileOutputStream("Promoter.dat");
            ObjectOutputStream outputFile = new ObjectOutputStream(file);
            for(int i=0; i<Promoters.size(); i++){
                outputFile.writeObject(Promoters.get(i));
                
            }
            outputFile.close();
            JOptionPane.showMessageDialog(null,"File Successfully Save");
            this.dispose();
            
        }
        catch(IOException e){
            JOptionPane.showMessageDialog(null,e.getMessage());
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        PromoterNameLabel = new javax.swing.JLabel();
        PromoterAgeLabel = new javax.swing.JLabel();
        PromoterBudgetLabel = new javax.swing.JLabel();
        WillPublishLabel = new javax.swing.JLabel();
        PromoterNameEntry = new javax.swing.JTextField();
        PromoterAgeEntry = new javax.swing.JTextField();
        PromoterBudgetEntry = new javax.swing.JTextField();
        checkBox = new javax.swing.JCheckBox();
        PromoterSaveButton = new javax.swing.JButton();
        PromoterCloseButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add New Promoter");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Create A New Promoter ");

        PromoterNameLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        PromoterNameLabel.setText("Name of Promoter");

        PromoterAgeLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        PromoterAgeLabel.setText("Age                         ");

        PromoterBudgetLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        PromoterBudgetLabel.setText("Budget ");

        WillPublishLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        WillPublishLabel.setText("Will Publish ?");

        PromoterNameEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PromoterNameEntryActionPerformed(evt);
            }
        });

        PromoterAgeEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PromoterAgeEntryActionPerformed(evt);
            }
        });

        PromoterBudgetEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PromoterBudgetEntryActionPerformed(evt);
            }
        });

        checkBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxActionPerformed(evt);
            }
        });

        PromoterCloseButton.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PromoterCloseButtonActionPerformed(evt);
            }
        });

        PromoterSaveButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        PromoterSaveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("Images/save.png"))); // NOI18N
        PromoterSaveButton.setText("Save");
        PromoterSaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PromoterSaveButtonActionPerformed(evt);
            }
        });

        PromoterCloseButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        PromoterCloseButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("Images/exit.png"))); // NOI18N
        PromoterCloseButton.setText("Close");
        PromoterCloseButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("Images/Person.png"))); // NOI18N
        jLabel6.setText("jLabel6");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(63, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(PromoterNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PromoterNameEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(PromoterAgeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PromoterAgeEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(PromoterBudgetLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(WillPublishLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(checkBox, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(PromoterBudgetEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(PromoterSaveButton)
                                .addGap(73, 73, 73)
                                .addComponent(PromoterCloseButton)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(125, 125, 125))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PromoterNameEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PromoterNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PromoterAgeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PromoterAgeEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PromoterBudgetEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PromoterBudgetLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(checkBox)
                    .addComponent(WillPublishLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PromoterSaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PromoterCloseButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(52, 52, 52))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PromoterNameEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PromoterNameEntryActionPerformed
        // TODO add your handling code here:
    }

    private void checkBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxActionPerformed
        // TODO add your handling code here:
    }

    private void PromoterBudgetEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PromoterBudgetEntryActionPerformed
        // TODO add your handling code here:
    }

    private void PromoterAgeEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PromoterAgeEntryActionPerformed
        // TODO add your handling code here:
    }
    private void PromoterCloseButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        this.dispose();


    }

    private void PromoterSaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PromoterSaveButtonActionPerformed
        // TODO add your handling code here:
        
        if(PromoterNameEntry.getText().isEmpty() || 
                PromoterAgeEntry.getText().isEmpty() ||
                PromoterBudgetEntry.getText().isEmpty() ){
            JOptionPane.showMessageDialog(null, "Please Enter All Fields");
        }
        else{
            String PromoterName = PromoterNameEntry.getText().trim();
            String PromoterAge = PromoterAgeEntry.getText().trim();
            String PromoterBudget = PromoterBudgetEntry.getText().trim();
            boolean WillPublish;
            WillPublish = checkBox.isSelected();
            
            Promoter Newpromoter = new Promoter(PromoterName,
                    Integer.parseInt(PromoterAge),
                    WillPublish,
                    Double.parseDouble(PromoterBudget));
            
            Promoters.add(Newpromoter);
            savePromoterToFile();
            
            
  
        }
        
        
        
        
    }//GEN-LAST:event_PromoterSaveButtonActionPerformed



    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddPromoter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddPromoter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddPromoter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddPromoter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddPromoter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField PromoterAgeEntry;
    private javax.swing.JLabel PromoterAgeLabel;
    private javax.swing.JTextField PromoterBudgetEntry;
    private javax.swing.JLabel PromoterBudgetLabel;
    private javax.swing.JButton PromoterCloseButton;
    private javax.swing.JTextField PromoterNameEntry;
    private javax.swing.JLabel PromoterNameLabel;
    private javax.swing.JButton PromoterSaveButton;
    private javax.swing.JLabel WillPublishLabel;
    private javax.swing.JCheckBox checkBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
