/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author user
 *
 */
import javax.swing.*;
import java.io.*;
import java.util.ArrayList;

public class AddSportsVenue extends javax.swing.JFrame {

    /**
     * Creates new form AddSportsVenue
     */
    ArrayList<SportsVenue> sportsVenue;


    /**
     * Creates new form AddTrainingVenue
     */
    public AddSportsVenue() {
        initComponents();
        sportsVenue = new ArrayList<SportsVenue>();
        poplulateArryList();
    }
    public void poplulateArryList(){
        try{
            FileInputStream file = new FileInputStream("SportsVenue.dat");
            ObjectInputStream inputFile = new ObjectInputStream(file);

            boolean endOfFile = false;

            while (!endOfFile){
                try{
                    sportsVenue.add((SportsVenue) inputFile.readObject());
                }
                catch(EOFException e){
                    endOfFile = true;

                }
                catch(Exception f){
                    JOptionPane.showMessageDialog(null,f.getMessage());

                }
            }
            inputFile.close();


        }
        catch(IOException e){
            JOptionPane.showMessageDialog(null,e.getMessage());
        }

    }
    public void saveVenueToFile(){
        try{
            FileOutputStream file = new FileOutputStream("SportsVenue.dat");
            ObjectOutputStream outputFile = new ObjectOutputStream(file);
            for(int i=0; i<sportsVenue.size(); i++){
                outputFile.writeObject(sportsVenue.get(i));

            }
            outputFile.close();
            JOptionPane.showMessageDialog(null,"File Successfully Save");
            this.dispose();

        }
        catch(IOException e){
            JOptionPane.showMessageDialog(null,e.getMessage());

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        VenueNameLabel = new javax.swing.JLabel();
        VenueSizeLabel = new javax.swing.JLabel();
        CompetAreaLabel = new javax.swing.JLabel();
        SpectAreaLabel = new javax.swing.JLabel();
        NumSecurityLabel = new javax.swing.JLabel();
        BasePriceLabel = new javax.swing.JLabel();
        LevelLabel = new javax.swing.JLabel();
        VenueNameEntry = new javax.swing.JTextField();
        VenueSizeEntry = new javax.swing.JTextField();
        CompetAreaEntry = new javax.swing.JTextField();
        SpectAreaEntry = new javax.swing.JTextField();
        NumSecurityEntry = new javax.swing.JTextField();
        BasePriceEntry = new javax.swing.JTextField();
        LevelEntry = new javax.swing.JTextField();
        SaveButton = new javax.swing.JButton();
        ExitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Add Sports Venue Information ");

        VenueNameLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        VenueNameLabel.setText("Venue Name");

        VenueSizeLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        VenueSizeLabel.setText("Venue Size");

        CompetAreaLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CompetAreaLabel.setText("Size of Compeititor Area");

        SpectAreaLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        SpectAreaLabel.setText("Size of Spectator Area");

        NumSecurityLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        NumSecurityLabel.setText("Number of Security ");

        BasePriceLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BasePriceLabel.setText("Base Price ");

        LevelLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LevelLabel.setText("Level ");

        VenueNameEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VenueNameEntryActionPerformed(evt);
            }
        });

        CompetAreaEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CompetAreaEntryActionPerformed(evt);
            }
        });

        BasePriceEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BasePriceEntryActionPerformed(evt);
            }
        });

        SaveButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        SaveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("Images/save.png"))); // NOI18N
        SaveButton.setText("Save");
        SaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButtonActionPerformed(evt);
            }
        });

        ExitButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ExitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("Images/exit.png"))); // NOI18N
        ExitButton.setText("Exit");
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(49, 49, 49)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(LevelLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(BasePriceLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(NumSecurityLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(SpectAreaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(VenueNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(VenueSizeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(CompetAreaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(VenueNameEntry, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                                                        .addComponent(VenueSizeEntry)
                                                        .addComponent(CompetAreaEntry)
                                                        .addComponent(SpectAreaEntry)
                                                        .addComponent(NumSecurityEntry)
                                                        .addComponent(BasePriceEntry)
                                                        .addComponent(LevelEntry)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap(208, Short.MAX_VALUE)
                                                .addComponent(SaveButton)
                                                .addGap(108, 108, 108)
                                                .addComponent(ExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(57, 57, 57)))
                                .addGap(173, 173, 173))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(VenueNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(VenueNameEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(VenueSizeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(VenueSizeEntry)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(CompetAreaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(13, 13, 13)
                                                .addComponent(CompetAreaEntry)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(SpectAreaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(7, 7, 7)
                                                .addComponent(SpectAreaEntry, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(NumSecurityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(NumSecurityEntry, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(BasePriceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(BasePriceEntry, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(LevelLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(7, 7, 7)
                                                .addComponent(LevelEntry)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(SaveButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(ExitButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>

    private void SaveButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        if(VenueNameEntry.getText().isEmpty() ||
                VenueSizeEntry.getText().isEmpty() ||
                CompetAreaEntry.getText().isEmpty() ||
                SpectAreaEntry.getText().isEmpty() ||
                BasePriceEntry.getText().isEmpty() ||
                NumSecurityEntry.getText().isEmpty()||
                LevelEntry.getText().isEmpty() ){
            JOptionPane.showMessageDialog(null, "Please Enter All Fields");
        }
        else{
            String VenueName = VenueNameEntry.getText().trim();
            String VenueSize = VenueSizeEntry.getText().trim();
            String VenuePrice = BasePriceEntry.getText().trim();
            String VennueLevel = LevelEntry.getText().trim();
            String CompetArea = CompetAreaEntry.getText().trim();
            String SpectArea = SpectAreaEntry.getText().trim();
            String NumSecurity = NumSecurityEntry.getText().trim();




            SportsVenue NewVenue = new SportsVenue(VenueName,
                    Double.parseDouble(CompetArea),
                    Double.parseDouble(SpectArea),Integer.parseInt(NumSecurity),Double.parseDouble(VenuePrice),
                    Integer.parseInt(VennueLevel));

            sportsVenue.add(NewVenue);

            saveVenueToFile();
        }
    }

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        this.dispose();

    }

    private void BasePriceEntryActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void VenueNameEntryActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void CompetAreaEntryActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddSportsVenue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddSportsVenue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddSportsVenue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddSportsVenue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddSportsVenue().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JTextField BasePriceEntry;
    private javax.swing.JLabel BasePriceLabel;
    private javax.swing.JTextField CompetAreaEntry;
    private javax.swing.JLabel CompetAreaLabel;
    private javax.swing.JButton ExitButton;
    private javax.swing.JTextField LevelEntry;
    private javax.swing.JLabel LevelLabel;
    private javax.swing.JTextField NumSecurityEntry;
    private javax.swing.JLabel NumSecurityLabel;
    private javax.swing.JButton SaveButton;
    private javax.swing.JTextField SpectAreaEntry;
    private javax.swing.JLabel SpectAreaLabel;
    private javax.swing.JTextField VenueNameEntry;
    private javax.swing.JLabel VenueNameLabel;
    private javax.swing.JTextField VenueSizeEntry;
    private javax.swing.JLabel VenueSizeLabel;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration
}
