/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import javax.swing.*;
import java.io.*;
import java.util.ArrayList;

/**
 *
 * @author user
 */
public class AddTrainingVenue extends javax.swing.JFrame {
    ArrayList<TrainingVenue> trainingVenue;


    /**
     * Creates new form AddTrainingVenue
     */
    public AddTrainingVenue() {
        initComponents();
        trainingVenue = new ArrayList<TrainingVenue>();
        poplulateArryList();
    }
    public void poplulateArryList(){
        try{
            FileInputStream file = new FileInputStream("TrainingVenue.dat");
            ObjectInputStream inputFile = new ObjectInputStream(file);

            boolean endOfFile = false;

            while (!endOfFile){
                try{
                    trainingVenue.add((TrainingVenue) inputFile.readObject());
                }
                catch(EOFException e){
                    endOfFile = true;

                }
                catch(Exception f){
                    JOptionPane.showMessageDialog(null,f.getMessage());

                }
            }
            inputFile.close();


        }
        catch(IOException e){
            JOptionPane.showMessageDialog(null,e.getMessage());
        }

    }
    public void saveVenueToFile(){
        try{
            FileOutputStream file = new FileOutputStream("TrainingVenue.dat");
            ObjectOutputStream outputFile = new ObjectOutputStream(file);
            for(int i=0; i<trainingVenue.size(); i++){
                outputFile.writeObject(trainingVenue.get(i));

            }
            outputFile.close();
            JOptionPane.showMessageDialog(null,"File Successfully Save");
            this.dispose();

        }
        catch(IOException e){
            JOptionPane.showMessageDialog(null,e.getMessage());

        }
    }


    /**
     * Creates new form AddTrainingVenue
     */


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        VenueNameLable = new javax.swing.JLabel();
        VenueSizeLabel = new javax.swing.JLabel();
        InstructAreaLabel = new javax.swing.JLabel();
        OtherAreaLabel = new javax.swing.JLabel();
        BasePriceLabel = new javax.swing.JLabel();
        LevelLable = new javax.swing.JLabel();
        VenueNameEntry = new javax.swing.JTextField();
        VenueSizeEntry = new javax.swing.JTextField();
        InstructAreaEntry = new javax.swing.JTextField();
        OtherAreaEntry = new javax.swing.JTextField();
        BasePriceEntry = new javax.swing.JTextField();
        LevelEntry = new javax.swing.JTextField();
        SaveButton = new javax.swing.JButton();
        ExitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Add Training Venue Information");

        VenueNameLable.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        VenueNameLable.setText("Venue Name");

        VenueSizeLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        VenueSizeLabel.setText("Veue Size");

        InstructAreaLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        InstructAreaLabel.setText("Size of Instructor Area");

        OtherAreaLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        OtherAreaLabel.setText("Size of Other Area");

        BasePriceLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BasePriceLabel.setText("Base Price");

        LevelLable.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LevelLable.setText("Level");

        SaveButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        SaveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("Images/save.png"))); // NOI18N
        SaveButton.setText("Save");
        SaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButtonActionPerformed(evt);
            }
        });

        ExitButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ExitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("Images/exit.png"))); // NOI18N
        ExitButton.setText("Exit");
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(251, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(195, 195, 195))
                        .addGroup(layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(VenueSizeEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(OtherAreaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(VenueSizeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(VenueNameLable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(BasePriceLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(LevelLable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(InstructAreaLabel))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(12, 12, 12)
                                                                .addComponent(VenueNameEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addComponent(SaveButton)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                                .addComponent(ExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(InstructAreaEntry, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(OtherAreaEntry, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(BasePriceEntry, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(LevelEntry, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(VenueNameEntry, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                                        .addComponent(VenueNameLable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(VenueSizeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(VenueSizeEntry, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(InstructAreaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(InstructAreaEntry, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(OtherAreaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(OtherAreaEntry, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(BasePriceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(BasePriceEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(LevelLable, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(LevelEntry, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(SaveButton)
                                        .addComponent(ExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    private void SaveButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        if(VenueNameEntry.getText().isEmpty() ||
                VenueSizeEntry.getText().isEmpty() ||
                InstructAreaEntry.getText().isEmpty() ||
                OtherAreaEntry.getText().isEmpty() ||
                BasePriceEntry.getText().isEmpty() ||
                LevelEntry.getText().isEmpty() ){
            JOptionPane.showMessageDialog(null, "Please Enter All Fields");
        }
        else{
            String VenueName = VenueNameEntry.getText().trim();
            String VenueSize = VenueSizeEntry.getText().trim();
            String VenuePrice = BasePriceEntry.getText().trim();
            String VennueLevel = LevelEntry.getText().trim();
            String InstructorEntry = InstructAreaEntry.getText().trim();
            String OtherArea = OtherAreaEntry.getText().trim();



            TrainingVenue NewVenue = new TrainingVenue(VenueName,
                    Double.parseDouble(InstructorEntry),
                    Double.parseDouble(OtherArea),Double.parseDouble(VenuePrice),
                    Integer.parseInt(VennueLevel));

            trainingVenue.add(NewVenue);

            saveVenueToFile();
        }
    }
    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        this.dispose();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddTrainingVenue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddTrainingVenue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddTrainingVenue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddTrainingVenue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddTrainingVenue().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JTextField BasePriceEntry;
    private javax.swing.JLabel BasePriceLabel;
    private javax.swing.JButton ExitButton;
    private javax.swing.JTextField InstructAreaEntry;
    private javax.swing.JLabel InstructAreaLabel;
    private javax.swing.JTextField LevelEntry;
    private javax.swing.JLabel LevelLable;
    private javax.swing.JTextField OtherAreaEntry;
    private javax.swing.JLabel OtherAreaLabel;
    private javax.swing.JButton SaveButton;
    private javax.swing.JTextField VenueNameEntry;
    private javax.swing.JLabel VenueNameLable;
    private javax.swing.JTextField VenueSizeEntry;
    private javax.swing.JLabel VenueSizeLabel;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration
}
