/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import java.io.EOFException;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class AddVenue extends javax.swing.JFrame {
    ArrayList<Venue> GeneralVenue;

    /**
     * Creates new form AddVenue
     */
    public AddVenue() {
        initComponents();
        GeneralVenue = new ArrayList<Venue>();
        poplulateArryList();
    }
    public void poplulateArryList(){
        try{
            FileInputStream file = new FileInputStream("GeneralVenue.dat");
            ObjectInputStream inputFile = new ObjectInputStream(file);

            boolean endOfFile = false;

            while (!endOfFile){
                try{
                    GeneralVenue.add((Venue) inputFile.readObject());
                }
                catch(EOFException e){
                    endOfFile = true;

                }
                catch(Exception f){
                    JOptionPane.showMessageDialog(null,f.getMessage());

                }
            }
            inputFile.close();


        }
        catch(IOException e){
            JOptionPane.showMessageDialog(null,e.getMessage());
        }

    }
    public void saveVenueToFile(){
        try{
            FileOutputStream file = new FileOutputStream("GeneralVenue.dat");
            ObjectOutputStream outputFile = new ObjectOutputStream(file);
            for(int i=0; i<GeneralVenue.size(); i++){
                outputFile.writeObject(GeneralVenue.get(i));

            }
            outputFile.close();
            JOptionPane.showMessageDialog(null,"File Successfully Save");
            this.dispose();

        }
        catch(IOException e){
            JOptionPane.showMessageDialog(null,e.getMessage());

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        VenueNameLabel = new javax.swing.JLabel();
        VenueSizeLabel = new javax.swing.JLabel();
        VenuePriceLabel = new javax.swing.JLabel();
        VenueLevelLabel = new javax.swing.JLabel();
        VenueNameEntry = new javax.swing.JTextField();
        VenueSizeEntry = new javax.swing.JTextField();
        VenuePriceEntry = new javax.swing.JTextField();
        VenueLevelEntry = new javax.swing.JTextField();
        SaveButton = new javax.swing.JButton();
        ExitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Add General Venue Information");

        VenueNameLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        VenueNameLabel.setText("Venue Name");

        VenueSizeLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        VenueSizeLabel.setText("Size");

        VenuePriceLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        VenuePriceLabel.setText("Price ");

        VenueLevelLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        VenueLevelLabel.setText("Level");

        VenueNameEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VenueNameEntryActionPerformed(evt);
            }
        });

        SaveButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        SaveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("Images/save.png"))); // NOI18N
        SaveButton.setText("Save");
        SaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButtonActionPerformed(evt);
            }
        });

        ExitButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ExitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("Images/exit.png"))); // NOI18N
        ExitButton.setText("Exit");
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(135, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(118, 118, 118))
                        .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(VenueNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                                                        .addComponent(VenueSizeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(VenuePriceLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(VenueLevelLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(VenueNameEntry)
                                                        .addComponent(VenueSizeEntry)
                                                        .addComponent(VenueLevelEntry, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                                                        .addComponent(VenuePriceEntry))
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(52, 52, 52)
                                                .addComponent(SaveButton)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(ExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(160, 160, 160))))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(VenueNameLabel)
                                        .addComponent(VenueNameEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(VenueSizeLabel)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(1, 1, 1)
                                                .addComponent(VenueSizeEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(VenuePriceLabel)
                                        .addComponent(VenuePriceEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(VenueLevelLabel)
                                        .addComponent(VenueLevelEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(SaveButton)
                                        .addComponent(ExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>

    private void VenueNameEntryActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void SaveButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        if(VenueNameEntry.getText().isEmpty() ||
                VenueSizeEntry.getText().isEmpty() ||
                VenuePriceEntry.getText().isEmpty() ||
                VenueLevelEntry.getText().isEmpty() ){
            JOptionPane.showMessageDialog(null, "Please Enter All Fields");
        }
        else{
            String VenueName = VenueNameEntry.getText().trim();
            String VenueSize = VenueSizeEntry.getText().trim();
            String VenuePrice = VenuePriceEntry.getText().trim();
            String VennueLevel = VenueLevelEntry.getText().trim();



            Venue NewVenue = new Venue(VenueName,
                    Double.parseDouble(VenueSize),
                    Double.parseDouble(VenuePrice),
                    Integer.parseInt(VennueLevel));

            GeneralVenue.add(NewVenue);

            saveVenueToFile();
        }


    }

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        this.dispose();
    }


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddVenue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddVenue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddVenue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddVenue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddVenue().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton ExitButton;
    private javax.swing.JButton SaveButton;
    private javax.swing.JTextField VenueLevelEntry;
    private javax.swing.JLabel VenueLevelLabel;
    private javax.swing.JTextField VenueNameEntry;
    private javax.swing.JLabel VenueNameLabel;
    private javax.swing.JTextField VenuePriceEntry;
    private javax.swing.JLabel VenuePriceLabel;
    private javax.swing.JTextField VenueSizeEntry;
    private javax.swing.JLabel VenueSizeLabel;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration
}
